use strum_macros::EnumIter;
#[derive(Clone, PartialEq, EnumIter)]
pub enum Effect {
    AntiGravity,
    Athletic,
    Balding,
    BrightEyed,
    Calming,
    CalorieDense,
    Cyclopean,
    Disorienting,
    Electrifying,
    Energizing,
    Euphoric,
    Explosive,
    Focused,
    Foggy,
    Gingeritis,
    Glowing,
    Jennerising,
    Laxative,
    LongFaced,
    Munchies,
    Paranoia,
    Refreshing,
    Schizophrenic,
    Sedating,
    SeizureInducing,
    Shrinking,
    Slippery,
    Smelly,
    Sneaky,
    Spicy,
    ThoughtProvoking,
    Toxic,
    TropicThunder,
    Zombifying,
}

macro_rules! to_foreground {
    ($r:expr, $g:expr, $b:expr) => {
        concat!("\x1b[38;2;", $r, ";", $g, ";", $b, "m")
    };
}

const RESET: &str = "\x1b[0m";

impl Effect {
    pub const fn addictiveness(&self) -> f32 {
        match self {
            Self::TropicThunder => 0.803,
            Self::Spicy => 0.665,
            Self::AntiGravity => 0.611,
            Self::Athletic => 0.607,
            Self::LongFaced => 0.607,
            Self::Zombifying => 0.598,
            Self::Glowing => 0.472,
            Self::ThoughtProvoking => 0.37,
            Self::Jennerising => 0.343,
            Self::Energizing => 0.34,
            Self::Shrinking => 0.336,
            Self::Sneaky => 0.327,
            Self::Slippery => 0.309,
            Self::Euphoric => 0.235,
            Self::Electrifying => 0.235,
            Self::BrightEyed => 0.2,
            Self::Focused => 0.104,
            Self::Refreshing => 0.104,
            Self::CalorieDense => 0.1,
            Self::Cyclopean => 0.1,
            Self::Foggy => 0.1,
            Self::Laxative => 0.1,
            Self::Munchies => 0.096,
            Self::Gingeritis => 0.,
            Self::Sedating => 0.,
            Self::Balding => 0.,
            Self::Calming => 0.,
            Self::Disorienting => 0.,
            Self::Explosive => 0.,
            Self::Paranoia => 0.,
            Self::Schizophrenic => 0.,
            Self::SeizureInducing => 0.,
            Self::Smelly => 0.,
            Self::Toxic => 0.,
        }
    }
    pub const fn multiplier(&self) -> f32 {
        match self {
            Self::Shrinking => 0.60,
            Self::Zombifying => 0.58,
            Self::Cyclopean => 0.56,
            Self::AntiGravity => 0.54,
            Self::LongFaced => 0.52,
            Self::Electrifying => 0.50,
            Self::Glowing => 0.48,
            Self::TropicThunder => 0.46,
            Self::ThoughtProvoking => 0.44,
            Self::Jennerising => 0.42,
            Self::BrightEyed => 0.40,
            Self::Spicy => 0.38,
            Self::Foggy => 0.36,
            Self::Slippery => 0.34,
            Self::Athletic => 0.32,
            Self::Balding => 0.30,
            Self::CalorieDense => 0.28,
            Self::Sedating => 0.26,
            Self::Sneaky => 0.24,
            Self::Energizing => 0.22,
            Self::Gingeritis => 0.20,
            Self::Euphoric => 0.18,
            Self::Focused => 0.16,
            Self::Refreshing => 0.14,
            Self::Munchies => 0.12,
            Self::Calming => 0.10,
            Self::Disorienting => 0.00,
            Self::Explosive => 0.00,
            Self::Laxative => 0.00,
            Self::Paranoia => 0.00,
            Self::Schizophrenic => 0.00,
            Self::SeizureInducing => 0.00,
            Self::Smelly => 0.00,
            Self::Toxic => 0.00,
        }
    }
    pub const fn name(&self) -> &'static str {
        match self {
            Self::AntiGravity => "Anti-Gravity",
            Self::Athletic => "Athletic",
            Self::Balding => "Balding",
            Self::BrightEyed => "Bright-Eyed",
            Self::Calming => "Calming",
            Self::CalorieDense => "Calorie-Dense",
            Self::Cyclopean => "Cyclopean",
            Self::Disorienting => "Disorienting",
            Self::Electrifying => "Electrifying",
            Self::Energizing => "Energizing",
            Self::Euphoric => "Euphoric",
            Self::Explosive => "Explosive",
            Self::Focused => "Focused",
            Self::Foggy => "Foggy",
            Self::Gingeritis => "Gingeritis",
            Self::Glowing => "Glowing",
            Self::Jennerising => "Jennerising",
            Self::Laxative => "Laxative",
            Self::LongFaced => "Long Faced",
            Self::Munchies => "Munchies",
            Self::Paranoia => "Paranoia",
            Self::Refreshing => "Refreshing",
            Self::Schizophrenic => "Schizophrenic",
            Self::Sedating => "Sedating",
            Self::SeizureInducing => "Seizure-Inducing",
            Self::Shrinking => "Shrinking",
            Self::Slippery => "Slippery",
            Self::Smelly => "Smelly",
            Self::Sneaky => "Sneaky",
            Self::Spicy => "Spicy",
            Self::ThoughtProvoking => "Thought-Provoking",
            Self::Toxic => "Toxic",
            Self::TropicThunder => "Tropic Thunder",
            Self::Zombifying => "Zombifying",
        }
    }
    pub const fn forground(&self) -> &'static str {
        match self {
            Self::AntiGravity => to_foreground!(35, 91, 203),
            Self::Athletic => to_foreground!(117, 200, 253),
            Self::Balding => to_foreground!(199, 146, 50),
            Self::BrightEyed => to_foreground!(190, 247, 253),
            Self::Calming => to_foreground!(254, 208, 155),
            Self::CalorieDense => to_foreground!(254, 132, 244),
            Self::Cyclopean => to_foreground!(254, 193, 116),
            Self::Disorienting => to_foreground!(254, 117, 81),
            Self::Electrifying => to_foreground!(85, 200, 253),
            Self::Energizing => to_foreground!(154, 254, 109),
            Self::Euphoric => to_foreground!(254, 234, 116),
            Self::Explosive => to_foreground!(254, 75, 64),
            Self::Focused => to_foreground!(117, 241, 253),
            Self::Foggy => to_foreground!(176, 176, 175),
            Self::Gingeritis => to_foreground!(254, 136, 41),
            Self::Glowing => to_foreground!(133, 228, 89),
            Self::Jennerising => to_foreground!(254, 141, 248),
            Self::Laxative => to_foreground!(118, 60, 37),
            Self::LongFaced => to_foreground!(254, 217, 97),
            Self::Munchies => to_foreground!(201, 110, 87),
            Self::Paranoia => to_foreground!(196, 103, 98),
            Self::Refreshing => to_foreground!(178, 254, 152),
            Self::Schizophrenic => to_foreground!(100, 90, 253),
            Self::Sedating => to_foreground!(107, 95, 216),
            Self::SeizureInducing => to_foreground!(254, 233, 0),
            Self::Shrinking => to_foreground!(182, 254, 218),
            Self::Slippery => to_foreground!(162, 223, 253),
            Self::Smelly => to_foreground!(125, 188, 49),
            Self::Sneaky => to_foreground!(123, 123, 123),
            Self::Spicy => to_foreground!(254, 107, 76),
            Self::ThoughtProvoking => to_foreground!(254, 160, 203),
            Self::Toxic => to_foreground!(95, 154, 49),
            Self::TropicThunder => to_foreground!(254, 159, 71),
            Self::Zombifying => to_foreground!(113, 171, 93),
        }
    }
    // TODO: make this const
    pub fn colord_name(&self) -> String {
        format!("{}{}{}", &self.forground(), &self.name(), RESET)
    }
}
