#[derive(Clone, PartialEq)]
pub enum Effect {
    AntiGravity,
    Athletic,
    Balding,
    BrightEyed,
    Calming,
    CalorieDense,
    Cyclopean,
    Disorienting,
    Electrifying,
    Energizing,
    Euphoric,
    Explosive,
    Focused,
    Foggy,
    Gingeritis,
    Glowing,
    Jennerising,
    Laxative,
    LongFaced,
    Munchies,
    Paranoia,
    Refreshing,
    Schizophrenic,
    Sedating,
    SeizureInducing,
    Shrinking,
    Slippery,
    Smelly,
    Sneaky,
    Spicy,
    ThoughtProvoking,
    Toxic,
    TropicThunder,
    Zombifying,
}

macro_rules! to_foreground {
    ($r:expr, $g:expr, $b:expr) => {
        concat!("\x1b[38;2;", $r, ";", $g, ";", $b, "m")
    };
}

const RESET: &str = "\x1b[0m";

impl Effect {
    pub const fn addictiveness(&self) -> f32 {
        match self {
            Effect::TropicThunder => 0.803,
            Effect::Spicy => 0.665,
            Effect::AntiGravity => 0.611,
            Effect::Athletic => 0.607,
            Effect::LongFaced => 0.607,
            Effect::Zombifying => 0.598,
            Effect::Glowing => 0.472,
            Effect::ThoughtProvoking => 0.37,
            Effect::Jennerising => 0.343,
            Effect::Energizing => 0.34,
            Effect::Shrinking => 0.336,
            Effect::Sneaky => 0.327,
            Effect::Slippery => 0.309,
            Effect::Euphoric => 0.235,
            Effect::Electrifying => 0.235,
            Effect::BrightEyed => 0.2,
            Effect::Focused => 0.104,
            Effect::Refreshing => 0.104,
            Effect::CalorieDense => 0.1,
            Effect::Cyclopean => 0.1,
            Effect::Foggy => 0.1,
            Effect::Laxative => 0.1,
            Effect::Munchies => 0.096,
            Effect::Gingeritis => 0.,
            Effect::Sedating => 0.,
            Effect::Balding => 0.,
            Effect::Calming => 0.,
            Effect::Disorienting => 0.,
            Effect::Explosive => 0.,
            Effect::Paranoia => 0.,
            Effect::Schizophrenic => 0.,
            Effect::SeizureInducing => 0.,
            Effect::Smelly => 0.,
            Effect::Toxic => 0.,
        }
    }
    pub const fn multiplier(&self) -> f32 {
        match self {
            Effect::Shrinking => 0.60,
            Effect::Zombifying => 0.58,
            Effect::Cyclopean => 0.56,
            Effect::AntiGravity => 0.54,
            Effect::LongFaced => 0.52,
            Effect::Electrifying => 0.50,
            Effect::Glowing => 0.48,
            Effect::TropicThunder => 0.46,
            Effect::ThoughtProvoking => 0.44,
            Effect::Jennerising => 0.42,
            Effect::BrightEyed => 0.40,
            Effect::Spicy => 0.38,
            Effect::Foggy => 0.36,
            Effect::Slippery => 0.34,
            Effect::Athletic => 0.32,
            Effect::Balding => 0.30,
            Effect::CalorieDense => 0.28,
            Effect::Sedating => 0.26,
            Effect::Sneaky => 0.24,
            Effect::Energizing => 0.22,
            Effect::Gingeritis => 0.20,
            Effect::Euphoric => 0.18,
            Effect::Focused => 0.16,
            Effect::Refreshing => 0.14,
            Effect::Munchies => 0.12,
            Effect::Calming => 0.10,
            Effect::Disorienting => 0.00,
            Effect::Explosive => 0.00,
            Effect::Laxative => 0.00,
            Effect::Paranoia => 0.00,
            Effect::Schizophrenic => 0.00,
            Effect::SeizureInducing => 0.00,
            Effect::Smelly => 0.00,
            Effect::Toxic => 0.00,
        }
    }
    pub const fn name(&self) -> &'static str {
        match self {
            Effect::AntiGravity => "Anti-Gravity",
            Effect::Athletic => "Athletic",
            Effect::Balding => "Balding",
            Effect::BrightEyed => "Bright-Eyed",
            Effect::Calming => "Calming",
            Effect::CalorieDense => "Calorie-Dense",
            Effect::Cyclopean => "Cyclopean",
            Effect::Disorienting => "Disorienting",
            Effect::Electrifying => "Electrifying",
            Effect::Energizing => "Energizing",
            Effect::Euphoric => "Euphoric",
            Effect::Explosive => "Explosive",
            Effect::Focused => "Focused",
            Effect::Foggy => "Foggy",
            Effect::Gingeritis => "Gingeritis",
            Effect::Glowing => "Glowing",
            Effect::Jennerising => "Jennerising",
            Effect::Laxative => "Laxative",
            Effect::LongFaced => "Long Faced",
            Effect::Munchies => "Munchies",
            Effect::Paranoia => "Paranoia",
            Effect::Refreshing => "Refreshing",
            Effect::Schizophrenic => "Schizophrenic",
            Effect::Sedating => "Sedating",
            Effect::SeizureInducing => "Seizure-Inducing",
            Effect::Shrinking => "Shrinking",
            Effect::Slippery => "Slippery",
            Effect::Smelly => "Smelly",
            Effect::Sneaky => "Sneaky",
            Effect::Spicy => "Spicy",
            Effect::ThoughtProvoking => "Thought-Provoking",
            Effect::Toxic => "Toxic",
            Effect::TropicThunder => "Tropic Thunder",
            Effect::Zombifying => "Zombifying",
        }
    }
    pub const fn forground(&self) -> &'static str {
        match self {
            Effect::AntiGravity => to_foreground!(35, 91, 203),
            Effect::Athletic => to_foreground!(117, 200, 253),
            Effect::Balding => to_foreground!(199, 146, 50),
            Effect::BrightEyed => to_foreground!(190, 247, 253),
            Effect::Calming => to_foreground!(254, 208, 155),
            Effect::CalorieDense => to_foreground!(254, 132, 244),
            Effect::Cyclopean => to_foreground!(254, 193, 116),
            Effect::Disorienting => to_foreground!(254, 117, 81),
            Effect::Electrifying => to_foreground!(85, 200, 253),
            Effect::Energizing => to_foreground!(154, 254, 109),
            Effect::Euphoric => to_foreground!(254, 234, 116),
            Effect::Explosive => to_foreground!(254, 75, 64),
            Effect::Focused => to_foreground!(117, 241, 253),
            Effect::Foggy => to_foreground!(176, 176, 175),
            Effect::Gingeritis => to_foreground!(254, 136, 41),
            Effect::Glowing => to_foreground!(133, 228, 89),
            Effect::Jennerising => to_foreground!(254, 141, 248),
            Effect::Laxative => to_foreground!(118, 60, 37),
            Effect::LongFaced => to_foreground!(254, 217, 97),
            Effect::Munchies => to_foreground!(201, 110, 87),
            Effect::Paranoia => to_foreground!(196, 103, 98),
            Effect::Refreshing => to_foreground!(178, 254, 152),
            Effect::Schizophrenic => to_foreground!(100, 90, 253),
            Effect::Sedating => to_foreground!(107, 95, 216),
            Effect::SeizureInducing => to_foreground!(254, 233, 0),
            Effect::Shrinking => to_foreground!(182, 254, 218),
            Effect::Slippery => to_foreground!(162, 223, 253),
            Effect::Smelly => to_foreground!(125, 188, 49),
            Effect::Sneaky => to_foreground!(123, 123, 123),
            Effect::Spicy => to_foreground!(254, 107, 76),
            Effect::ThoughtProvoking => to_foreground!(254, 160, 203),
            Effect::Toxic => to_foreground!(95, 154, 49),
            Effect::TropicThunder => to_foreground!(254, 159, 71),
            Effect::Zombifying => to_foreground!(113, 171, 93),
        }
    }
    // TODO: make this const
    pub fn colord_name(&self) -> String {
        format!("{}{}{}", &self.forground(), &self.name(), RESET)
    }
}
